[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_files = [
    "pyproject.toml:version",
]
update_changelog_on_bump = true
changelog_format = "markdown"
changelog_file = "CHANGELOG.md"
tag_format = "v$version"
bump_message = "bump: version $current_version → $new_version" 