# Read the Docs configuration file for study
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - pandoc
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-latex-extra
  jobs:
    pre_build:
      # Ensure proper environment setup
      - python -m pip install --upgrade pip
      - pip install uv
    post_install:
      # Install project dependencies with docs extras
      - uv sync --extra docs
      # Install additional dependencies for notebooks
      - uv add marimo markdown pymdown-extensions packaging linkify-it-py
    post_build:
      # Optional: Generate HTML exports of marimo notebooks
      - cd docs/tutorials && uv run python export_notebooks.py

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Optional but recommended, declare the formats you want to build
formats:
  - pdf
  - htmlzip
  - epub
